package net.mahdirazavi.java.toolkit.util;

import java.io.PrintWriter;
import java.io.StringWriter;

/**
 * The Class Exceptions.
 * 
 */
public class Exceptions {

  /**
   * Gets the stack trace from a Throwable as a String.
   *
   * <p>
   * This method uses {@link Throwable#printStackTrace(java.io.PrintWriter)}.
   * </p>
   *
   * @param throwable The <code>Throwable</code> to be examined
   * @return The stack trace as generated by the exception's
   *         <code>printStackTrace(PrintWriter)</code> method
   */
  public static String getStackTrace(final Throwable throwable) {
    final StringWriter sw = new StringWriter();
    final PrintWriter pw = new PrintWriter(sw, true);
    throwable.printStackTrace(pw);
    return sw.getBuffer().toString();
  }

}
